env:
  browser: true
  commonjs: true
  es2021: true
  jest/globals: true
  node: true
extends:
  - airbnb-base
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
plugins:
  - '@typescript-eslint'
  - 'jest'
rules: {
  'no-empty-function': ["error", { "allow": ["constructors"] }],
  'no-useless-constructor': 'off',
  'import/extensions': ['error',
    "ignorePackages",
    {
      "js": "never",
      "jsx": "never",
      "ts": "never",
      "tsx": "never"
    }
  ],
}
settings:
  import/resolver:
    node:
      extensions:
        - ".js"
        - ".jsx"
        - ".json"
        - ".ts"
        - ".tsx"
